//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonTCG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int MatchID { get; set; }
        public string PlayerOne { get; set; }
        public string PlayerTwo { get; set; }
        public int PlayerTwoDamage { get; set; }
        public int PlayerOneDamage { get; set; }
        public string PlayerOneDeck { get; set; }
        public string PlayerTwoDeck { get; set; }
        public string Winner { get; set; }
        public System.DateTime Date { get; set; }
    }
}
