//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonTCG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public int DeckID { get; set; }
    
        public virtual Deck Deck { get; set; }
    }
}
